# Generated by Django 3.2.9 on 2022-03-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='furnished',
            field=models.CharField(default='Give brief description', max_length=400),
        ),
        migrations.AddField(
            model_name='request',
            name='security',
            field=models.CharField(default='explain', max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='power_vailability',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='water_availability',
            field=models.BooleanField(default=False),
        ),
    ]
