# Generated by Django 3.2.9 on 2022-03-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20220305_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='trans_id',
            field=models.CharField(default='explain', max_length=255),
        ),
    ]
