# Generated by Django 3.2.9 on 2022-03-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_request_trans_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='furnished',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='request',
            name='security',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='trans_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
